version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    target-branch: "main"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    target-branch: "main"

  - package-ecosystem: "docker"
    directory: "/src/python_template/api/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    target-branch: "main"
