services:
  postgresql:
    image: postgres@sha256:4aabea78cf39b90e834caf3af7d602a18565f6fe2508705c8d01aa63245c2e20 # 18.1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: python_template
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - ./database:/docker-entrypoint-initdb.d:ro

volumes:
  postgresql:
